export * from './implementations/affirmative/present/simple/affirmative-present-simple'
export * from './implementations/affirmative/present/continuous/affirmative-present-continuous'
export * from './implementations/affirmative/present/perfect/affirmative-present-perfect'
export * from './implementations/affirmative/present/perfect-continuous/affirmative-present-perfect-continuous'
export * from './implementations/affirmative/past/simple/affirmative-past-simple'
export * from './implementations/affirmative/past/continuous/affirmative-past-continuous'
